[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "gcc", "gnumake", "libtool", "autoconf", "automake", "libsodium"]

[phases.install]
cmds = ["npm install --include=optional"]

[start]
cmd = "node --dns-result-order=ipv4first src/index.js"
